### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by myxxmikeyxx** [codekoch/mediakit_RaspberryPi#1]
Does this still work on current raspberry pi OS or do I need to use an older version like the 2018 one mentioned?
Also do you have just an install for the wireless display part? I don't need the other features, just the windows PC ability to connect to it for wireless display.

**Comment by codekoch** [comment]
Sorry, this project is no longer maintained. You can give it a try, but have so solve any problems on your own.

**Comment by myxxmikeyxx** [comment]
No problem. Thank you for the info.
